"use server";

import getDB from "@/db";

const create = async () => {
  const db = await getDB();

  await db
    .insertInto("confluenceVideos")
    .values([
      {
        id: "2024-04-19-upside-down",
        song: "Upside Down",
        venue: "Rivoli Film Festival",
        performanceOrder: 1,
        date: "04/19/2024",
        rootUrl: "https://r2.everly.page/confluence/04-19 Rivoli/1. Upside Down/",
      },
      {
        id: "2024-04-19-until-i-found-you",
        song: "Until I Found You",
        venue: "Rivoli Film Festival",
        performanceOrder: 2,
        date: "04/19/2024",
        rootUrl: "https://r2.everly.page/confluence/04-19 Rivoli/2. Until I Found You/",
      },
      {
        id: "2024-04-19-ho-hey",
        song: "Ho Hey",
        venue: "Rivoli Film Festival",
        performanceOrder: 3,
        date: "04/19/2024",
        rootUrl: "https://r2.everly.page/confluence/04-19 Rivoli/3. Ho Hey/",
      },
      {
        id: "2024-04-19-brown-eyed-girl",
        song: "Brown Eyed Girl",
        venue: "Rivoli Film Festival",
        performanceOrder: 4,
        date: "04/19/2024",
        rootUrl: "https://r2.everly.page/confluence/04-19 Rivoli/4. Brown Eyed Girl/",
      },
      {
        id: "2024-04-19-the-night-we-met",
        song: "The Night We Met",
        venue: "Rivoli Film Festival",
        performanceOrder: 5,
        date: "04/19/2024",
        rootUrl: "https://r2.everly.page/confluence/04-19 Rivoli/5. The Night We Met/",
      },
      {
        id: "2024-04-19-groove-is-in-the-heart",
        song: "Groove Is In The Heart",
        venue: "Rivoli Film Festival",
        performanceOrder: 6,
        date: "04/19/2024",
        rootUrl: "https://r2.everly.page/confluence/04-19 Rivoli/6. Groove Is In The Heart/",
      },
      {
        id: "2024-04-19-everlong",
        song: "Everlong",
        venue: "Rivoli Film Festival",
        performanceOrder: 7,
        date: "04/19/2024",
        rootUrl: "https://r2.everly.page/confluence/04-19 Rivoli/7. Everlong/",
      },
      {
        id: "2024-04-19-sweet-dreams",
        song: "Sweet Dreams (Are Made of This)",
        venue: "Rivoli Film Festival",
        performanceOrder: 8,
        date: "04/19/2024",
        rootUrl: "https://r2.everly.page/confluence/04-19 Rivoli/8. Sweet Dreams/",
      },
      {
        id: "2024-04-19-cant-stop-the-feeling",
        song: "Can't Stop The Feeling!",
        venue: "Rivoli Film Festival",
        performanceOrder: 9,
        date: "04/19/2024",
        rootUrl: "https://r2.everly.page/confluence/04-19 Rivoli/9. Can't Stop The Feeling/",
      },

      {
        id: "2024-04-26-upside-down",
        song: "Upside Down",
        venue: "Central High School",
        performanceOrder: 1,
        date: "04/26/2024",
        rootUrl: "https://r2.everly.page/confluence/04-26 Central/1. Upside Down/",
      },
      {
        id: "2024-04-26-ho-hey",
        song: "Ho Hey",
        venue: "Central High School",
        performanceOrder: 2,
        date: "04/26/2024",
        rootUrl: "https://r2.everly.page/confluence/04-26 Central/2. Ho Hey/",
      },
      {
        id: "2024-04-26-groove-is-in-the-heart",
        song: "Groove Is In The Heart",
        venue: "Central High School",
        performanceOrder: 3,
        date: "04/26/2024",
        rootUrl: "https://r2.everly.page/confluence/04-26 Central/3. Groove Is In The Heart/",
      },
      {
        id: "2024-04-26-until-i-found-you",
        song: "Until I Found You",
        venue: "Central High School",
        performanceOrder: 4,
        date: "04/26/2024",
        rootUrl: "https://r2.everly.page/confluence/04-26 Central/4. Until I Found You/",
      },
      {
        id: "2024-04-26-everlong",
        song: "Everlong",
        venue: "Central High School",
        performanceOrder: 5,
        date: "04/26/2024",
        rootUrl: "https://r2.everly.page/confluence/04-26 Central/5. Everlong/",
      },
      {
        id: "2024-04-26-aint-it-fun",
        song: "Ain't It Fun",
        venue: "Central High School",
        performanceOrder: 6,
        date: "04/26/2024",
        rootUrl: "https://r2.everly.page/confluence/04-26 Central/6. Ain't It Fun/",
      },
      {
        id: "2024-04-26-cant-stop-the-feeling",
        song: "Can't Stop The Feeling!",
        venue: "Central High School",
        performanceOrder: 7,
        date: "04/26/2024",
        rootUrl: "https://r2.everly.page/confluence/04-26 Central/7. Can't Stop The Feeling/",
      },

      {
        id: "2024-05-03-brown-eyed-girl",
        song: "Brown Eyed Girl",
        venue: "Logan High School",
        performanceOrder: 1,
        date: "05/03/2024",
        rootUrl: "https://r2.everly.page/confluence/05-03 Logan/1. Brown Eyed Girl/",
      },
      {
        id: "2024-05-03-the-night-we-met",
        song: "The Night We Met",
        venue: "Logan High School",
        performanceOrder: 2,
        date: "05/03/2024",
        rootUrl: "https://r2.everly.page/confluence/05-03 Logan/2. The Night We Met/",
      },
      {
        id: "2024-05-03-groove-is-in-the-heart",
        song: "Groove Is In The Heart",
        venue: "Logan High School",
        performanceOrder: 3,
        date: "05/03/2024",
        rootUrl: "https://r2.everly.page/confluence/05-03 Logan/3. Groove Is In The Heart/",
      },
      {
        id: "2024-05-03-everlong",
        song: "Everlong",
        venue: "Logan High School",
        performanceOrder: 4,
        date: "05/03/2024",
        rootUrl: "https://r2.everly.page/confluence/05-03 Logan/4. Everlong/",
      },

      {
        id: "2024-05-10-ho-hey",
        song: "Ho Hey",
        venue: "Rivoli Full Show",
        performanceOrder: 1,
        date: "05/10/2024",
        rootUrl: "https://r2.everly.page/confluence/05-10 Rivoli/1. Ho Hey/",
      },
      {
        id: "2024-05-10-upside-down",
        song: "Upside Down",
        venue: "Rivoli Full Show",
        performanceOrder: 2,
        date: "05/10/2024",
        rootUrl: "https://r2.everly.page/confluence/05-10 Rivoli/2. Upside Down/",
      },
      {
        id: "2024-05-10-until-i-found-you",
        song: "Until I Found You",
        venue: "Rivoli Full Show",
        performanceOrder: 3,
        date: "05/10/2024",
        rootUrl: "https://r2.everly.page/confluence/05-10 Rivoli/3. Until I Found You/",
      },
      {
        id: "2024-05-10-build-me-up-buttercup",
        song: "Build Me Up Buttercup",
        venue: "Rivoli Full Show",
        performanceOrder: 4,
        date: "05/10/2024",
        rootUrl: "https://r2.everly.page/confluence/05-10 Rivoli/4. Build Me Up Buttercup/",
      },
      {
        id: "2024-05-10-groove-is-in-the-heart",
        song: "Groove Is In The Heart",
        venue: "Rivoli Full Show",
        performanceOrder: 5,
        date: "05/10/2024",
        rootUrl: "https://r2.everly.page/confluence/05-10 Rivoli/5. Groove Is In The Heart/",
      },
      {
        id: "2024-05-10-the-night-we-met",
        song: "The Night We Met",
        venue: "Rivoli Full Show",
        performanceOrder: 6,
        date: "05/10/2024",
        rootUrl: "https://r2.everly.page/confluence/05-10 Rivoli/6. The Night We Met/",
      },
      {
        id: "2024-05-10-everlong",
        song: "Everlong",
        venue: "Rivoli Full Show",
        performanceOrder: 7,
        date: "05/10/2024",
        rootUrl: "https://r2.everly.page/confluence/05-10 Rivoli/7. Everlong/",
      },
      {
        id: "2024-05-10-aint-it-fun",
        song: "Ain't It Fun",
        venue: "Rivoli Full Show",
        performanceOrder: 8,
        date: "05/10/2024",
        rootUrl: "https://r2.everly.page/confluence/05-10 Rivoli/8. Ain't It Fun/",
      },
      {
        id: "2024-05-10-brown-eyed-girl",
        song: "Brown Eyed Girl",
        venue: "Rivoli Full Show",
        performanceOrder: 9,
        date: "05/10/2024",
        rootUrl: "https://r2.everly.page/confluence/05-10 Rivoli/9. Brown Eyed Girl/",
      },
      {
        id: "2024-05-10-sweet-dreams",
        song: "Sweet Dreams (Are Made of This)",
        venue: "Rivoli Full Show",
        performanceOrder: 10,
        date: "05/10/2024",
        rootUrl: "https://r2.everly.page/confluence/05-10 Rivoli/10. Sweet Dreams/",
      },
      {
        id: "2024-05-10-carry-on-wayward-son",
        song: "Carry On Wayward Son",
        venue: "Rivoli Full Show",
        performanceOrder: 11,
        date: "05/10/2024",
        rootUrl: "https://r2.everly.page/confluence/05-10 Rivoli/11. Carry On Wayward Son/",
      },
      {
        id: "2024-05-10-cant-stop-the-feeling",
        song: "Can't Stop The Feeling!",
        venue: "Rivoli Full Show",
        performanceOrder: 12,
        date: "05/10/2024",
        rootUrl: "https://r2.everly.page/confluence/05-10 Rivoli/12. Can't Stop The Feeling/",
      },
      {
        id: "2024-05-10-groove-is-in-the-heart-encore",
        song: "Groove Is In The Heart",
        suffix: "(Encore)",
        venue: "Rivoli Full Show",
        performanceOrder: 13,
        date: "05/10/2024",
        rootUrl: "https://r2.everly.page/confluence/05-10 Rivoli/13. Groove Is In The Heart (Encore)/",
      },

      {
        id: "2024-05-19-upside-down",
        song: "Upside Down",
        venue: "The Main",
        performanceOrder: 1,
        date: "05/19/2024",
        rootUrl: "https://r2.everly.page/confluence/05-19 The Main/1. Upside Down/",
      },
      {
        id: "2024-05-19-ho-hey",
        song: "Ho Hey",
        venue: "The Main",
        performanceOrder: 2,
        date: "05/19/2024",
        rootUrl: "https://r2.everly.page/confluence/05-19 The Main/2. Ho Hey/",
      },
      {
        id: "2024-05-19-until-i-found-you",
        song: "Until I Found You",
        venue: "The Main",
        performanceOrder: 3,
        date: "05/19/2024",
        rootUrl: "https://r2.everly.page/confluence/05-19 The Main/3. Until I Found You/",
      },
      {
        id: "2024-05-19-groove-is-in-the-heart",
        song: "Groove Is In The Heart",
        venue: "The Main",
        performanceOrder: 4,
        date: "05/19/2024",
        rootUrl: "https://r2.everly.page/confluence/05-19 The Main/4. Groove Is In The Heart/",
      },
      {
        id: "2024-05-19-build-me-up-buttercup",
        song: "Build Me Up Buttercup",
        venue: "The Main",
        performanceOrder: 5,
        date: "05/19/2024",
        rootUrl: "https://r2.everly.page/confluence/05-19 The Main/5. Build Me Up Buttercup/",
      },
      {
        id: "2024-05-19-the-night-we-met",
        song: "The Night We Met",
        venue: "The Main",
        performanceOrder: 6,
        date: "05/19/2024",
        rootUrl: "https://r2.everly.page/confluence/05-19 The Main/6. The Night We Met/",
      },
      {
        id: "2024-05-19-aint-it-fun",
        song: "Ain't It Fun",
        venue: "The Main",
        performanceOrder: 7,
        date: "05/19/2024",
        rootUrl: "https://r2.everly.page/confluence/05-19 The Main/7. Ain't It Fun/",
      },
      {
        id: "2024-05-19-everlong",
        song: "Everlong",
        venue: "The Main",
        performanceOrder: 8,
        date: "05/19/2024",
        rootUrl: "https://r2.everly.page/confluence/05-19 The Main/8. Everlong/",
      },
      {
        id: "2024-05-19-brown-eyed-girl",
        song: "Brown Eyed Girl",
        venue: "The Main",
        performanceOrder: 9,
        date: "05/19/2024",
        rootUrl: "https://r2.everly.page/confluence/05-19 The Main/9. Brown Eyed Girl/",
      },
      {
        id: "2024-05-19-sweet-dreams",
        song: "Sweet Dreams (Are Made of This)",
        venue: "The Main",
        performanceOrder: 10,
        date: "05/19/2024",
        rootUrl: "https://r2.everly.page/confluence/05-19 The Main/10. Sweet Dreams/",
      },
      {
        id: "2024-05-19-carry-on-wayward-son",
        song: "Carry On Wayward Son",
        venue: "The Main",
        performanceOrder: 11,
        date: "05/19/2024",
        rootUrl: "https://r2.everly.page/confluence/05-19 The Main/11. Carry On My Wayward Son/",
      },
      {
        id: "2024-05-19-cant-stop-the-feeling",
        song: "Can't Stop The Feeling!",
        venue: "The Main",
        performanceOrder: 12,
        date: "05/19/2024",
        rootUrl: "https://r2.everly.page/confluence/05-19 The Main/12. Can't Stop The Feeling/",
      },
      {
        id: "2024-05-19-jump-in-the-line",
        song: "Jump In the Line",
        venue: "The Main",
        performanceOrder: 13,
        date: "05/19/2024",
        rootUrl: "https://r2.everly.page/confluence/05-19 The Main/13. Jump In The Line/",
      },

      {
        id: "2024-06-09-upside-down",
        song: "Upside Down",
        venue: "Riverside Park",
        performanceOrder: 1,
        date: "06-09-2024",
        rootUrl: "https://r2.everly.page/confluence/06-09 Riverside/1. Upside Down/",
      },
      {
        id: "2024-06-09-ho-hey",
        song: "Ho Hey",
        venue: "Riverside Park",
        performanceOrder: 2,
        date: "06-09-2024",
        rootUrl: "https://r2.everly.page/confluence/06-09 Riverside/2. Ho Hey/",
      },
      {
        id: "2024-06-09-until-i-found-you",
        song: "Until I Found You",
        venue: "Riverside Park",
        performanceOrder: 3,
        date: "06-09-2024",
        rootUrl: "https://r2.everly.page/confluence/06-09 Riverside/3. Until I Found You/",
      },
      {
        id: "2024-06-09-groove-is-in-the-heart",
        song: "Groove Is In The Heart",
        venue: "Riverside Park",
        performanceOrder: 4,
        date: "06-09-2024",
        rootUrl: "https://r2.everly.page/confluence/06-09 Riverside/4. Groove Is In The Heart/",
      },
      {
        id: "2024-06-09-build-me-up-buttercup",
        song: "Build Me Up Buttercup",
        venue: "Riverside Park",
        performanceOrder: 5,
        date: "06-09-2024",
        rootUrl: "https://r2.everly.page/confluence/06-09 Riverside/5. Build Me Up Buttercup/",
      },
      {
        id: "2024-06-09-the-night-we-met",
        song: "The Night We Met",
        venue: "Riverside Park",
        performanceOrder: 6,
        date: "06-09-2024",
        rootUrl: "https://r2.everly.page/confluence/06-09 Riverside/6. The Night We Met/",
      },
      {
        id: "2024-06-09-aint-it-fun",
        song: "Ain't It Fun",
        venue: "Riverside Park",
        performanceOrder: 7,
        date: "06-09-2024",
        rootUrl: "https://r2.everly.page/confluence/06-09 Riverside/7. Ain't It Fun/",
      },
      {
        id: "2024-06-09-everlong",
        song: "Everlong",
        venue: "Riverside Park",
        performanceOrder: 8,
        date: "06-09-2024",
        rootUrl: "https://r2.everly.page/confluence/06-09 Riverside/8. Everlong/",
      },
      {
        id: "2024-06-09-brown-eyed-girl",
        song: "Brown Eyed Girl",
        venue: "Riverside Park",
        performanceOrder: 9,
        date: "06-09-2024",
        rootUrl: "https://r2.everly.page/confluence/06-09 Riverside/9. Brown Eyed Girl/",
      },
      {
        id: "2024-06-09-sweet-dreams",
        song: "Sweet Dreams (Are Made of This)",
        venue: "Riverside Park",
        performanceOrder: 10,
        date: "06-09-2024",
        rootUrl: "https://r2.everly.page/confluence/06-09 Riverside/10. Sweet Dreams/",
      },
      {
        id: "2024-06-09-carry-on-wayward-son",
        song: "Carry On Wayward Son",
        venue: "Riverside Park",
        performanceOrder: 11,
        date: "06-09-2024",
        rootUrl: "https://r2.everly.page/confluence/06-09 Riverside/11. Carry On Wayward Son/",
      },
      {
        id: "2024-06-09-cant-stop-the-feeling",
        song: "Can't Stop The Feeling!",
        venue: "Riverside Park",
        performanceOrder: 12,
        date: "06-09-2024",
        rootUrl: "https://r2.everly.page/confluence/06-09 Riverside/12. Can't Stop The Feeling/",
      },
      {
        id: "2024-06-09-jump-in-the-line",
        song: "Jump In the Line",
        venue: "Riverside Park",
        performanceOrder: 13,
        date: "06-09-2024",
        rootUrl: "https://r2.everly.page/confluence/06-09 Riverside/13. Jump In The Line/",
      },

      {
        id: "2024-06-20-ho-hey",
        song: "Ho Hey",
        venue: "Moon Tunes",
        performanceOrder: 1,
        date: "06-20-2024",
        rootUrl: "https://r2.everly.page/confluence/06-20 Moon Tunes/1. Ho Hey/",
      },
      {
        id: "2024-06-20-aint-it-fun",
        song: "Ain't It Fun",
        venue: "Moon Tunes",
        performanceOrder: 2,
        date: "06-20-2024",
        rootUrl: "https://r2.everly.page/confluence/06-20 Moon Tunes/2. Ain't It Fun/",
      },
      {
        id: "2024-06-20-brown-eyed-girl",
        song: "Brown Eyed Girl",
        venue: "Moon Tunes",
        performanceOrder: 3,
        date: "06-20-2024",
        rootUrl: "https://r2.everly.page/confluence/06-20 Moon Tunes/3. Brown Eyed Girl/",
      },
      {
        id: "2024-06-20-carry-on-wayward-son",
        song: "Carry On Wayward Son",
        venue: "Moon Tunes",
        performanceOrder: 4,
        date: "06-20-2024",
        rootUrl: "https://r2.everly.page/confluence/06-20 Moon Tunes/4. Carry On/",
      },
      {
        id: "2024-06-20-groove-is-in-the-heart",
        song: "Groove Is In The Heart",
        venue: "Moon Tunes",
        performanceOrder: 5,
        date: "06-20-2024",
        rootUrl: "https://r2.everly.page/confluence/06-20 Moon Tunes/5. Groove Is In The Heart/",
      },

      {
        id: "2024-08-10-aint-it-fun",
        song: "Ain't It Fun",
        venue: "Ashley For The Arts",
        performanceOrder: 1,
        date: "08-10-2024",
        rootUrl: "https://r2.everly.page/confluence/08-10 Ashley For The Arts/1. Ain't It Fun/",
      },
      {
        id: "2024-08-10-brown-eyed-girl",
        song: "Brown Eyed Girl",
        venue: "Ashley For The Arts",
        performanceOrder: 2,
        date: "08-10-2024",
        rootUrl: "https://r2.everly.page/confluence/08-10 Ashley For The Arts/2. Brown Eyed Girl/",
      },
      {
        id: "2024-08-10-carry-on-wayward-son",
        song: "Carry On Wayward Son",
        venue: "Ashley For The Arts",
        performanceOrder: 3,
        date: "08-10-2024",
        rootUrl: "https://r2.everly.page/confluence/08-10 Ashley For The Arts/3. Carry On Wayward Son/",
      },

      {
        id: "2024-09-14-everlong",
        song: "Everlong",
        venue: "Vernon County Fair",
        performanceOrder: 1,
        date: "09-14-2024",
        rootUrl: "https://r2.everly.page/confluence/09-14 Vernon County Fair/1. Everlong/",
      },
      {
        id: "2024-09-14-upside-down",
        song: "Upside Down",
        venue: "Vernon County Fair",
        performanceOrder: 2,
        date: "09-14-2024",
        rootUrl: "https://r2.everly.page/confluence/09-14 Vernon County Fair/2. Upside Down/",
      },
      {
        id: "2024-09-14-build-me-up-buttercup",
        song: "Build Me Up Buttercup",
        venue: "Vernon County Fair",
        performanceOrder: 3,
        date: "09-14-2024",
        rootUrl: "https://r2.everly.page/confluence/09-14 Vernon County Fair/3. Build Me Up Buttercup/",
      },
      {
        id: "2024-09-14-ho-hey",
        song: "Ho Hey",
        venue: "Vernon County Fair",
        performanceOrder: 4,
        date: "09-14-2024",
        rootUrl: "https://r2.everly.page/confluence/09-14 Vernon County Fair/4. Ho Hey/",
      },
      {
        id: "2024-09-14-brown-eyed-girl",
        song: "Brown Eyed Girl",
        venue: "Vernon County Fair",
        performanceOrder: 5,
        date: "09-14-2024",
        rootUrl: "https://r2.everly.page/confluence/09-14 Vernon County Fair/5. Brown Eyed Girl/",
      },
      {
        id: "2024-09-14-aint-it-fun",
        song: "Ain't It Fun",
        venue: "Vernon County Fair",
        performanceOrder: 6,
        date: "09-14-2024",
        rootUrl: "https://r2.everly.page/confluence/09-14 Vernon County Fair/6. Ain't It Fun/",
      },
      {
        id: "2024-09-14-carry-on-wayward-son",
        song: "Carry On Wayward Son",
        venue: "Vernon County Fair",
        performanceOrder: 7,
        date: "09-14-2024",
        rootUrl: "https://r2.everly.page/confluence/09-14 Vernon County Fair/7. Carry On Wayward Son/",
      },
    ])
    .execute();
};

export default create;
